version: "3"
services:
  front_end:
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - internal-network
  back_end:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - internal-network
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - internal-network
    volumes:
      - mongo-data:/data/db
  mongo-web:
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge

volumes:
  mongo-data:
